# Generated by Django 3.0.5 on 2020-09-03 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.UUIDField(default=uuid.uuid4)),
                ('text', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, choices=[('m', 'Gemeld'), ('i', 'In afwachting van behandeling'), ('h', 'On hold'), ('o', 'Afgehandeld'), ('s', 'Gesplitst'), ('reopened', 'Heropend'), ('b', 'In behandeling'), ('ingepland', 'Ingepland'), ('ready to send', 'Te verzenden naar extern systeem'), ('a', 'Geannuleerd'), ('closure requested', 'Verzoek tot afhandeling'), ('sent', 'Verzonden naar extern systeem'), ('send failed', 'Verzending naar extern systeem mislukt'), ('done external', 'Melding is afgehandeld in extern systeem'), ('reopen requested', 'Verzoek tot heropenen')], default='m', max_length=20)),
                ('category_level_name1', models.CharField(max_length=255)),
                ('category_level_name2', models.CharField(max_length=255)),
                ('category_level_name3', models.CharField(max_length=255)),
                ('category_level_name4', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
